language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: bryceahill@gmail.com
  api_key:
    secure: rXAvdHoxl4/6HUEyHmQR2Vtx0JWmytYO4SB1QQbh3CVkEqEWOKhM6nlTmOeaAqaU4/CNej/DdYGmBSRJH5dIVnqEOOivGr93XFuQkjmOFqEoYTMgarWNVUUGXIbS59ecAQSPUJJ8vIGND5g0LgC69NB84xtdBUe7Vm82O1vghpQ=
  on:
    tags: true
    repo: brycehill/ns-upload
